// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SplitEditor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSplitEditorPackageString = "e23c9b8f-c3d4-4772-ab0a-9e01ec879485";
        public static Guid guidSplitEditorPackage = new Guid(guidSplitEditorPackageString);

        public const string guidSplitEditorPackageCmdSetString = "a5b0267f-a896-40cf-8761-ea107ab2fdc1";
        public static Guid guidSplitEditorPackageCmdSet = new Guid(guidSplitEditorPackageCmdSetString);

        public const string guidImagesString = "de2120f7-8c4e-4cbe-b74f-36fd9b358eed";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DoNothingCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}